// <auto-generated />
using System;
using EncuentraAtuMascota.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EncuentraAtuMascota.Migrations
{
    [DbContext(typeof(EncuentraAtuMascotaContext))]
    [Migration("20181110220048_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EncuentraAtuMascota.Models.MiMascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Edad")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<byte[]>("FotoMascota")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("NombreDueno")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<string>("Tamaño")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("MiMascota");
                });

            modelBuilder.Entity("EncuentraAtuMascota.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Sexo");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
